"""Update Sighting model field names

Revision ID: 087cfb7993ac
Revises: 9db0d6b139cf
Create Date: 2025-05-07 10:15:53.195024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087cfb7993ac'
down_revision = '9db0d6b139cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_guess', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('observed_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('photos', sa.String(), nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('image')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('photos')
        batch_op.drop_column('observed_on')
        batch_op.drop_column('place_guess')

    # ### end Alembic commands ###
