"""Add species_id to sightings table

Revision ID: 40c143081ae8
Revises: 60fac57d22d1
Create Date: 2025-04-22 16:04:13.459542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c143081ae8'
down_revision = '60fac57d22d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sightings_species_id_species'), 'species', ['species_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sightings_species_id_species'), type_='foreignkey')
        batch_op.drop_column('species_id')

    # ### end Alembic commands ###
