"""switch to password hashing

Revision ID: 4a105e6cdbb4
Revises: 8f915c5c68cb
Create Date: 2025-05-03 10:39:28.836063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a105e6cdbb4'
down_revision = '8f915c5c68cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        # Drop the password column
        batch_op.drop_column('password')
        # Add the password_hash column
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('_password_hash')
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###
